version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: bazario-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bazario
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: bazario-redis
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: bazario-app
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bazario
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"