# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App Info
info.app.name=Bazario Backend
info.app.description=Multi-vendor E-Commerce Backend
info.app.version=1.0.0
info.developer.name=Nikhil Singh

spring.datasource.url=jdbc:mysql://localhost:3306/bazario
spring.datasource.username=springstudent
spring.datasource.password=springstudent



spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

bazariobackend.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.timeout=2000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

# Rate Limiting
app.rate.limit=10
app.rate.limit.duration=60
